name: Audit live site
icon: check-circle
description: Run lighthouse CI on actions

branding:
  icon: "check-square"
  color: "yellow"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: daniellop1/lighthouse@master
      with:
        url: 'https://jarv.is/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
        
    - name: Audit Netlify deploy preview
      uses: daniellop1/lighthouse@master
      with:
        netlify_site: 'goofy-hopper-9b17d1.netlify.app'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
